# CAUTION:
#   Not all features of a generic GitHub action is supported: https://github.com/actions/runner/issues/646
#
# **What does Composite Run Steps Not Support**
#
# We don't support setting conditionals, continue-on-error, timeout-minutes, "uses", and secrets on individual steps within a composite action right now.
#
# (Note: we do support these attributes being set in workflows for a step that uses a composite run steps action)
#

name: accum-inpage-downloads
description: 'in page downloads value request and accumulation'

inputs:
  query_url:
    description: 'URL to query a page with downloads value'
    required: true

  downloads_sed_regexp:
    description: 'Sed regexp to match the downloads value'
    required: true
    # example:
    #   `s/.*Downloaded:[^0-9]*([0-9.]+).*/\1/p`

  curl_flags:
    description: 'additional curl flags'
    # example:
    #   `-H 'Cache-Control: no-cache'`

  deps_repo_owner:
    description: 'Owner of a repository used to checkout dependencies'
    required: true

  stat_entity_path:
    description: 'Statistic entity path to request'
    required: true

  output_repo_owner:
    description: 'Owner of a repository used to output the statistic'
    required: true

  output_repo:
    description: 'Repository name used to output the statistic'
    required: true

  output_repo_branch:
    description: 'Repository branch used to output the statistic'
    default: master

  output_repo_dir:
    description: 'Output repository relative directory path to store requested and accumulated statistic'
    required: true
    # examples:
    # - traffic/downloads/plugin

  output_repo_write_token:
    description: 'PAT token to the output repository with write/push access rights'
    required: true

runs:
  using: "composite"
  steps:
    # step is required to workaround variable expansion in variables
    - name: declare dependent variables
      shell: bash
      run: |
        echo "stats_dir=${{ inputs.output_repo_dir }}" >> $GITHUB_ENV
        echo "stats_json=${{ inputs.output_repo_dir }}/latest.json" >> $GITHUB_ENV
        echo "stat_entity_path=${{ inputs.stat_entity_path }}" >> $GITHUB_ENV
        echo "query_url=${{ inputs.query_url }}" >> $GITHUB_ENV
        echo "downloads_sed_regexp=${{ inputs.downloads_sed_regexp }}" >> $GITHUB_ENV
        echo "curl_flags=${{ inputs.curl_flags }}" >> $GITHUB_ENV

    - name: allocate directories
      shell: bash
      run: |
        mkdir $GITHUB_WORKSPACE/gh-workflow $GITHUB_WORKSPACE/inpage-downloads
        echo "WORKFLOW_TEMPDIR=$(mktemp -d)" >> $GITHUB_ENV

    - name: checkout gh-workflow
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.deps_repo_owner }}/gh-workflow
        path:       gh-workflow

    - name: checkout inpage-downloads
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}
        ref:        ${{ inputs.output_repo_branch }}
        path:       inpage-downloads
        token:      ${{ inputs.output_repo_write_token }}

    # NOTE:
    #   Several features below are commented out because is not supported in a composite action runnner:
    #     * conditionals
    #     * continue-on-error
    #

    - name: accumulate ${{ inputs.stat_entity_path }}
      id: accum-downloads
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/inpage-downloads
        chmod ug+x $GITHUB_WORKSPACE/gh-workflow/bash/inpage/accum-downloads.sh
        $GITHUB_WORKSPACE/gh-workflow/bash/inpage/accum-downloads.sh
        # caution: no operation after that line if non zero exit code happens above

    - name: commit inpage-downloads
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/inpage-downloads
        git add .
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git commit -m "Automated update: ${{ inputs.stat_entity_path }}"

    - name: push inpage-downloads
      uses: ad-m/github-push-action@master
      with:
        repository:   ${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}
        branch:       ${{ inputs.output_repo_branch }}
        directory:    inpage-downloads
        github_token: ${{ inputs.output_repo_write_token }}
