# Tutorial to use with: https://github.com/andry81-devops/github-accum-stats
#

name: accum-inpage-downloads
description: 'GitHub composite action to request and accumulate downloads statistic from a value on a web page'

inputs:
  query_url:
    description: 'URL to query a page with downloads value'
    required: true

  downloads_sed_regexp:
    description: 'Sed regexp to match the downloads value'
    required: true
    # example:
    #   `s/.*Downloaded:[^0-9]*([0-9.]+).*/\1/p`

  curl_flags:
    description: 'additional curl flags'
    # example:
    #   `-H 'Cache-Control: no-cache'`

  deps_repo_owner:
    description: 'Owner of a repository used to checkout dependencies'
    required: true

  deps_repo_branch:
    description: 'Repository branch used to checkout dependencies'
    default: master

  deps_repo_read_token:
    description: 'PAT token to a repository used to checkout dependencies'
    default: ${{ github.token }}

  stat_entity_path:
    description: 'Statistic entity path to request'
    required: true

  output_repo_owner:
    description: 'Owner of a repository used to output the statistic'
    required: true

  output_repo:
    description: 'Repository name used to output the statistic'
    required: true

  output_repo_branch:
    description: 'Repository branch used to output the statistic'
    default: master

  output_repo_dir:
    description: 'Output repository relative directory path to store requested and accumulated statistic'
    required: true
    # examples:
    # - traffic/downloads/plugin

  output_repo_write_token:
    description: 'PAT token to the output repository with write/push access rights'
    required: true

  env:
    description: environment variables
    # See dependent repositories and scripts for details.
    # examples:
    #   CONTINUE_ON_INVALID_INPUT=1
    #   CONTINUE_ON_EMPTY_CHANGES=1
    #   CONTINUE_ON_RESIDUAL_CHANGES=1
    #   ENABLE_GENERATE_CHANGELOG_FILE=1
    #   ENABLE_PRINT_CURL_RESPONSE_ON_ERROR=1
    #   ENABLE_COMMIT_MESSAGE_DATE_WITH_TIME=1  # insert the time string in format HH:MMZ additionally after the date in each commit message
    #   CHANGELOG_FILE=changelog.txt

runs:
  using: "composite"
  steps:
    # step is required to workaround variable expansion in variables
    - name: declare dependent variables
      shell: bash
      run: |
        echo "GH_WORKFLOW_ROOT=$GITHUB_WORKSPACE/gh-workflow" >> $GITHUB_ENV

    - name: checkout gh-workflow@${{ inputs.deps_repo_branch }}
      uses: andry81-devops/gh-action--git-checkout@master
      with:
        repository: ${{ inputs.deps_repo_owner }}/gh-workflow
        ref:        ${{ inputs.deps_repo_branch }}
        path:       gh-workflow
        token:      ${{ inputs.deps_repo_read_token }}

        mkdir-p: >-
          ${{ env.GH_WORKFLOW_ROOT }}

    - name: update permissions
      shell: bash
      run: |
        chmod ug+x $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh
        chmod ug+x $GH_WORKFLOW_ROOT/bash/github/print-notice.sh
        chmod ug+x $GH_WORKFLOW_ROOT/bash/inpage/accum-downloads.sh

    # step is required to pass environment variables externally
    - name: declare variables from lists
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          ${{ inputs.env }}

    - name: variables validation
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          "CHANGELOG_FILE=${CHANGELOG_FILE:-"changelog.txt"}"

    - name: declare local variables
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          "CHANGELOG_FILE=$GITHUB_WORKSPACE/inpage-downloads/${{ inputs.output_repo_dir }}/$CHANGELOG_FILE" \
          "stats_dir=$GITHUB_WORKSPACE/inpage-downloads/${{ inputs.output_repo_dir }}" \
          "stat_entity_path=${{ inputs.stat_entity_path }}" \
          "query_url=${{ inputs.query_url }}" \
          "downloads_sed_regexp=${{ inputs.downloads_sed_regexp }}" \
          "curl_flags=${{ inputs.curl_flags }}"

    - name: declare local variables
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/set-env-from-args.sh \
          "changelog_dir=${CHANGELOG_FILE%/*}"

    - name: head annotations
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/github/print-notice.sh \
          "output repo dir: https://github.com/${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}/tree/${{ inputs.output_repo_branch }}/${{ inputs.output_repo_dir }}"

    - name: checkout inpage-downloads@${{ inputs.output_repo_branch }}
      uses: andry81-devops/gh-action--git-checkout@master
      with:
        repository: ${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}
        ref:        ${{ inputs.output_repo_branch }}
        path:       inpage-downloads
        token:      ${{ inputs.output_repo_write_token }}

        mkdir-p: >-
          ${{ inputs.output_repo_dir }}
          ${{ env.changelog_dir }}

    - name: accumulate ${{ inputs.stat_entity_path }}
      id: accum-downloads
      shell: bash
      run: |
        $GH_WORKFLOW_ROOT/bash/inpage/accum-downloads.sh
        # caution: no operation after that line if non zero exit code happens above

    - name: commit inpage-downloads
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/inpage-downloads
        git add .
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git commit -m "A/U: $COMMIT_MESSAGE_DATE_TIME_PREFIX: ${COMMIT_MESSAGE_PREFIX}${COMMIT_MESSAGE_PREFIX:+" | "}$COMMIT_MESSAGE_SUFFIX"

    - name: push inpage-downloads
      uses: ad-m/github-push-action@master
      with:
        repository:   ${{ inputs.output_repo_owner }}/${{ inputs.output_repo }}
        branch:       ${{ inputs.output_repo_branch }}
        directory:    inpage-downloads
        github_token: ${{ inputs.output_repo_write_token }}
